modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/LordGrimmauld/createintegration/issues"
logoFile="createintegration_logo.png"
[[mods]]
modId="create-integration-redux"
version="0.1.0"
displayName="Create Integration Redux"
displayURL=""
credits="Thanks to Grimmauld for the original mod"
authors="bytearray"
description='''This is a stripped down version of the create integration mod for 1.16.5'''
[[dependencies.createintegration]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.createintegration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)" #keep updated
    ordering="NONE"
    side="BOTH"
[[dependencies.createintegration]]
    modId="create"
    mandatory=true
    versionRange="[mc1.16.5_v0.3.1,)" #keep updated
    ordering="NONE"
    side="BOTH"
